In [ ]:
%tensorflow_version 2.x

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
!wget https://www.dropbox.com/sh/kpf9z73woodfssv/AAAw1_JIzpuVvwteJCma0xMla?dl=0

--2020-05-12 13:46:21--  https://www.dropbox.com/sh/kpf9z73woodfssv/AAAw1_JIzpuVvwteJCma0xMla?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.3.1, 2620:100:6021:1::a27d:4101
Connecting to www.dropbox.com (www.dropbox.com)|162.125.3.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /sh/raw/kpf9z73woodfssv/AAAw1_JIzpuVvwteJCma0xMla [following]
--2020-05-12 13:46:22--  https://www.dropbox.com/sh/raw/kpf9z73woodfssv/AAAw1_JIzpuVvwteJCma0xMla
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc28fede5e3cd74d340637d33f8c.dl.dropboxusercontent.com/zip_download_get/Aa8poY6uH4cxhXiLFzVnUp3Zl1WHA14h5ncgEdh5t8MReLNmcqhEv4nlCH_S2MIY_SlcqHEUlqzfBPa00e0ArEIUcHWlL-YiKER6Lz2EfdE4zA [following]
--2020-05-12 13:46:22--  https://uc28fede5e3cd74d340637d33f8c.dl.dropboxusercontent.com/zip_download_get/Aa8poY6uH4cxhXiLFzVnUp3Zl1WHA14h5ncgEdh5t8MReLNmcqhEv4nlCH_S2MIY_SlcqHEUlqzfBPa00e0

In [ ]:
labelspath='AAAw1_JIzpuVvwteJCma0xMla?dl=0'

In [ ]:
labelspath

'AAAw1_JIzpuVvwteJCma0xMla?dl=0'

In [ ]:
labels=pd.read_csv(labelspath, sep=',' , encoding='latin1')

In [ ]:
labels

PK  ... target
0           00002165364db923c7e6  ...    0.0
1           000032939017120e6e44  ...    0.0
2           0000412ca6e4628ce2cf  ...    0.0
3           000042bf85aa498cd78e  ...    0.0
4           0000455dfa3e01eae3af  ...    0.0
...                          ...  ...    ...
1306119     ffffd48fb36b63db010c  ...    0.0
1306120     ffffec519fa37cf60c78  ...    0.0
1306121     ffffed09fedb5088744a  ...    0.0
1306122  PKÐÞ¾±´>g´>gPK  ...    NaN
1306123                      ?g  ...    NaN

[1306124 rows x 3 columns]

In [ ]:
labels.shape

(1306124, 3)

In [ ]:
labels.columns

Index(['PK', 'question_text', 'target'], dtype='object')

In [ ]:
labels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1306124 entries, 0 to 1306123
Data columns (total 3 columns):
 #   Column         Non-Null Count    Dtype  
---  ------         --------------    -----  
 0   PK          1306124 non-null  object 
 1   question_text  1306122 non-null  object 
 2   target         1306122 non-null  float64
dtypes: float64(1), object(2)
memory usage: 29.9+ MB


In [ ]:
labels['target'].value_counts()

0.0    1225312
1.0      80810
Name: target, dtype: int64

In [ ]:
labels[labels['target'].isnull()]

PK question_text  target
1306122  PKÐÞ¾±´>g´>gPK           NaN     NaN
1306123                      ?g           NaN     NaN

In [ ]:
labels.dropna(axis=0, how='any', thresh=None, subset=None, inplace=True)

In [ ]:
labels

PK  ... target
0        00002165364db923c7e6  ...    0.0
1        000032939017120e6e44  ...    0.0
2        0000412ca6e4628ce2cf  ...    0.0
3        000042bf85aa498cd78e  ...    0.0
4        0000455dfa3e01eae3af  ...    0.0
...                       ...  ...    ...
1306117  ffffcc4e2331aaf1e41e  ...    0.0
1306118  ffffd431801e5a2f4861  ...    0.0
1306119  ffffd48fb36b63db010c  ...    0.0
1306120  ffffec519fa37cf60c78  ...    0.0
1306121  ffffed09fedb5088744a  ...    0.0

[1306122 rows x 3 columns]

In [ ]:
!wget http://nlp.stanford.edu/data/glove.42B.300d.zip
# downloading and unzipping will take some time 

--2020-05-12 14:02:31--  http://nlp.stanford.edu/data/glove.42B.300d.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.42B.300d.zip [following]
--2020-05-12 14:02:31--  https://nlp.stanford.edu/data/glove.42B.300d.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/glove.42B.300d.zip [following]
--2020-05-12 14:02:32--  http://downloads.cs.stanford.edu/nlp/data/glove.42B.300d.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1877800501 (1.7G) [application/zip]
Sav

In [ ]:
!unzip /content/glove.42B.300d.zip

Archive:  /content/glove.42B.300d.zip
  inflating: glove.42B.300d.txt      


In [ ]:
!rm /content/glove.42B.300d.zip #removing zip file after unzipping

In [ ]:
embeding_index={}

f=open('glove.42B.300d.txt',encoding='utf-8')

for line in f:
  #reading one line
    values=line.split() #splitting the 1st line or string with spaces,will give list of len(301).1 word and 300 nos.
    word=values[0] # word (starting word of line) would be the 0th elemant
    coefs=np.asarray(values[1:],dtype='float32') #values[1:]=corresponding 300 dim vectors.from1 to 300
    embeding_index[word]=coefs
f.close()
# this again will take good amount of time

In [ ]:
from sklearn.model_selection import train_test_split
data_train,data_test=train_test_split(labels,test_size=0.2)

In [ ]:
x_train=data_train['question_text']
y_train=data_train['target']
x_test=data_test['question_text']
y_test=data_test['target']

In [ ]:
from nltk import word_tokenize

In [ ]:
import nltk #Natural Language Toolkit
nltk.download('punkt')
#q-punkt

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
sent_lens=[len(word_tokenize(x)) for x in x_train]

In [ ]:
np.percentile(sent_lens,99)

44.0

In [ ]:
max_len=44 #every sentence or every review wwill have only 44 words

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Model
from tensorflow.keras.layers import LeakyReLU
from tensorflow.keras.layers import Flatten
from tensorflow.keras import regularizers
from tensorflow.keras.layers import Lambda,Conv1D, MaxPooling1D,Activation, Dense,BatchNormalization,Input,Embedding,Dropout
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.layers import LSTM

In [ ]:
tk=Tokenizer(char_level=False,split=' ') #spliting sentences with spaces

tk.fit_on_texts(x_train) #

seq_train=tk.texts_to_sequences(x_train) #getting unique words in text
seq_test=tk.texts_to_sequences(x_test) #unique words in text

In [ ]:
x_train[924911]

'How must one overcome stage fright and give a strong presentation?'

In [ ]:
seq_train[0]

[9, 714, 56, 1052, 1709, 17972, 10, 149, 4, 841, 4394]

In [ ]:
vocab_size=len(tk.word_index)

In [ ]:
vocab_size

196271

In [ ]:
#tk.word_index #index dictionary with every word

In [ ]:
seq_train_matrix=sequence.pad_sequences(seq_train,maxlen=max_len) #padding/truncating sentences/reviews tomake it of size 44
seq_test_matrix=sequence.pad_sequences(seq_test,maxlen=max_len)

In [ ]:
seq_train_matrix.shape

(1044897, 44)

In [ ]:
seq_train_matrix

array([[    0,     0,     0, ...,     4,   841,  4394],
       [    0,     0,     0, ...,     7,  2031,    17],
       [    0,     0,     0, ..., 64550,   671, 13254],
       ...,
       [    0,     0,     0, ...,   171,     6,  1711],
       [    0,     0,     0, ...,  3205,    28,  1820],
       [    0,     0,     0, ...,    77,    49,  2027]], dtype=int32)

In [ ]:
# creating our own embedding matrix to bring down the size to 300
# we'll use 300 D vector representation of the words from pretrained embedding index 
# that we downloaded 

embedding_matrix=np.zeros((vocab_size+1,300)) #numpy matrix of size (2754,300).each row representing one word

for word,i in tk.word_index.items(): #word will become 'the' and index will become '1'
    embed_vector=embeding_index.get(word) #this would be glove vector for word 'the'
    if embed_vector is not None:
        embedding_matrix[i]=embed_vector #1st row of the embeding matrix is being updated by the glove vector word 'the'
        
# if there are specific words which are not present in pretrained embedding 
# their weights will remain 0. if there are too many such words 
# then you should probably not use pretrained embeddings 

In [ ]:
embedding_matrix

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.20838   , -0.14932001, -0.017528  , ..., -0.54066002,
         0.21199   , -0.0094357 ],
       [ 0.13877   , -0.0021201 , -0.091039  , ...,  0.024614  ,
         0.46514001,  0.11363   ],
       ...,
       [ 0.30577001,  0.19886   , -0.24507999, ..., -0.10191   ,
         0.66777003,  0.11696   ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.34402001, -0.10271   ,  0.4797    , ..., -1.08060002,
         0.15107   ,  0.2282    ]])

In [ ]:
inputs=Input(name='text_input',shape=[max_len]) #input will be 44 dim and 2d matrix

embed=Embedding(vocab_size+1,300,input_length=max_len,mask_zero=True,
                weights=[embedding_matrix],trainable=False)(inputs)  #300 is op we want #not to train the embending matrix because its already trained

lstm_layer=LSTM(50)(embed)

dense1=Dense(10,activation='relu')(lstm_layer)

drop=Dropout(0.2)(dense1)

final_layer=Dense(1,activation='sigmoid')(drop)

model=Model(inputs=inputs,outputs=final_layer)

In [ ]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
text_input (InputLayer)      [(None, 44)]              0         
_________________________________________________________________
embedding (Embedding)        (None, 44, 300)           58881600  
_________________________________________________________________
lstm (LSTM)                  (None, 50)                70200     
_________________________________________________________________
dense (Dense)                (None, 10)                510       
_________________________________________________________________
dropout (Dropout)            (None, 10)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 58,952,321
Trainable params: 70,721
Non-trainable params: 58,881,600
____________________________________________

In [ ]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(seq_train_matrix,y_train.values,validation_data=[seq_test_matrix,y_test.values],epochs=10,class_weight={0:1,1:12},
          batch_size=50)

Epoch 1/10
20898/20898 [==============================] - 872s 42ms/step - loss: 0.4795 - accuracy: 0.8946 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 2/10
20898/20898 [==============================] - 874s 42ms/step - loss: 0.4144 - accuracy: 0.9034 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 3/10
20898/20898 [==============================] - 867s 41ms/step - loss: 0.3792 - accuracy: 0.9061 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 4/10
20898/20898 [==============================] - 870s 42ms/step - loss: 0.3515 - accuracy: 0.9071 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 5/10
20898/20898 [==============================] - 881s 42ms/step - loss: 0.3311 - accuracy: 0.9093 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 6/10
20898/20898 [==============================] - 875s 42ms/step - loss: 0.3128 - accuracy: 0.9107 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 7/10
20898/20898 [==============================] - 

In [ ]:
p=model.predict(seq_test_matrix)

In [ ]:
.p

array([[3.5429001e-04],
       [5.4492721e-06],
       [2.5454164e-04],
       ...,
       [1.4835787e-05],
       [7.0789158e-01],
       [1.1752033e-05]], dtype=float32)

In [ ]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,p)

0.9568435895553999